FROM maven:3.2-jdk-7

RUN adduser --disabled-password --gecos '' snfcdmi
ADD .   /home/snfcdmi
WORKDIR /home/snfcdmi
RUN chown -R snfcdmi:snfcdmi .

USER snfcdmi
CMD id -a; echo; ls -al; echo; mvn -e package

