FROM maven:3.2-jdk-7

RUN adduser --disabled-password --gecos '' snfcdmi
USER snfcdmi

ENV APPHOME /home/snfcdmi
WORKDIR $APPHOME
COPY pom.xml $APPHOME/
RUN mvn dependency:resolve
RUN mvn compile || true; mvn package || true

COPY . $APPHOME/

CMD mvn -e install

